Repository development-ping/UNION-back, pull requests merged in 2024-10, with the labels that each got.

#77 feat: 모임 수정 API (#76)
  src/main/java/com/develop_ping/union/common/error/ErrorCode.java
  src/main/java/com/develop_ping/union/common/error/ErrorHandlingController.java
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/request/GatheringListCommand.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringDetailInfo.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringInfo.java
  src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/domain/strategy/GatheringDateSortStrategy.java
  src/main/java/com/develop_ping/union/gathering/exception/GatheringPermissionDeniedException.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringRepository.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
  src/main/java/com/develop_ping/union/gathering/presentation/dto/request/GatheringUpdateRequest.java
  src/main/java/com/develop_ping/union/party/domain/PartyManager.java
  src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
Labels: feat

#78 Feat/#71 reply comment
  src/main/java/com/develop_ping/union/comment/domain/CommentManager.java
  src/main/java/com/develop_ping/union/comment/domain/dto/CommentCommand.java
  src/main/java/com/develop_ping/union/comment/domain/dto/CommentInfo.java
  src/main/java/com/develop_ping/union/comment/domain/dto/CommentListInfo.java
  src/main/java/com/develop_ping/union/comment/domain/entity/Comment.java
  src/main/java/com/develop_ping/union/comment/domain/service/CommentService.java
  src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
  src/main/java/com/develop_ping/union/comment/exception/CommenterMismatchException.java
  src/main/java/com/develop_ping/union/comment/infra/CommentManagerImpl.java
  src/main/java/com/develop_ping/union/comment/infra/CommentRepository.java
  src/main/java/com/develop_ping/union/comment/presentation/CommentController.java
  src/main/java/com/develop_ping/union/comment/presentation/dto/request/CommentCreationRequest.java
  src/main/java/com/develop_ping/union/comment/presentation/dto/response/CommentDetailResponse.java
  src/main/java/com/develop_ping/union/comment/presentation/dto/response/CommentListResponse.java
  src/main/java/com/develop_ping/union/common/error/ErrorCode.java
  src/main/java/com/develop_ping/union/common/error/ErrorHandlingController.java
Labels: feat, refactor

#83 refactor: 댓글 논리 삭제 1단계(#82)
  src/main/java/com/develop_ping/union/comment/domain/dto/CommentCommand.java
  src/main/java/com/develop_ping/union/comment/domain/service/CommentService.java
  src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
  src/main/java/com/develop_ping/union/comment/presentation/CommentController.java
Labels: refactor

#87 feat: 모임 가입 API (#86)
  src/main/java/com/develop_ping/union/common/error/ErrorCode.java
  src/main/java/com/develop_ping/union/common/error/ErrorHandlingController.java
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/exception/ParticipantLimitExceededException.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringRepository.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
  src/main/java/com/develop_ping/union/party/domain/PartyManager.java
  src/main/java/com/develop_ping/union/party/domain/entity/Party.java
  src/main/java/com/develop_ping/union/party/exception/AlreadyJoinedException.java
  src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
  src/main/java/com/develop_ping/union/party/infra/PartyRepository.java
Labels: feat
