Repository development-ping/UNION-back, pull requests merged in 2024-11, with the labels that each got.

#93 feat: 모임 나가기 API (#92)
  src/main/java/com/develop_ping/union/common/error/ErrorCode.java
  src/main/java/com/develop_ping/union/common/error/ErrorHandlingController.java
  src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/exception/OwnerCannotExitException.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
  src/main/java/com/develop_ping/union/party/domain/PartyManager.java
  src/main/java/com/develop_ping/union/party/exception/ParticipationNotFoundException.java
  src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
  src/main/java/com/develop_ping/union/party/infra/PartyRepository.java
Labels: feat

#100 feat: 내가 작성한 모임글 리스트 API (#98)
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringRepository.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
Labels: feat

#105 refactor: comment, post, photo의 log 메시지 수정(#104)
  src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
  src/main/java/com/develop_ping/union/photo/domain/service/PhotoServiceImpl.java
  src/main/java/com/develop_ping/union/post/domain/service/PostServiceImpl.java
Labels: refactor

#112 feat: 댓글 수 기능 구현 및 하드코딩 제거(#111)
  src/main/java/com/develop_ping/union/comment/domain/CommentManager.java
  src/main/java/com/develop_ping/union/comment/domain/dto/CommentListInfo.java
  src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
  src/main/java/com/develop_ping/union/comment/infra/CommentManagerImpl.java
  src/main/java/com/develop_ping/union/comment/infra/CommentRepository.java
  src/main/java/com/develop_ping/union/comment/presentation/CommentController.java
  src/main/java/com/develop_ping/union/comment/presentation/dto/response/CommentListResponse.java
  src/main/java/com/develop_ping/union/post/domain/dto/info/PostInfo.java
  src/main/java/com/develop_ping/union/post/domain/dto/info/PostListInfo.java
  src/main/java/com/develop_ping/union/post/domain/service/PostServiceImpl.java
  src/main/java/com/develop_ping/union/post/presentation/PostListController.java
  src/main/java/com/develop_ping/union/post/presentation/dto/response/PostDetailResponse.java
  src/main/java/com/develop_ping/union/post/presentation/dto/response/PostListResponse.java
Labels: feat, refactor

#115 fix: post list 응답에 post type 필드 추가(#114)
  src/main/java/com/develop_ping/union/post/domain/dto/info/PostListInfo.java
  src/main/java/com/develop_ping/union/post/presentation/dto/response/PostListResponse.java
Labels: fix

#119 feat: 게시글 좋아요 관련 기능 구현(#118)
  src/main/java/com/develop_ping/union/post/domain/dto/info/PostReactionInfo.java
  src/main/java/com/develop_ping/union/post/domain/service/PostService.java
  src/main/java/com/develop_ping/union/post/domain/service/PostServiceImpl.java
  src/main/java/com/develop_ping/union/post/presentation/PostController.java
  src/main/java/com/develop_ping/union/post/presentation/dto/response/PostReactionResponse.java
  src/main/java/com/develop_ping/union/reaction/presentation/ReactionController.java
  src/main/java/com/develop_ping/union/reaction/presentation/dto/PostReactionResponse.java
Labels: feat

#122 feat: 모임 리스트 불러올 때 정보 추가 (#121)
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringListInfo.java
  src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
  src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringListResponse.java
  src/main/java/com/develop_ping/union/party/domain/PartyManager.java
  src/main/java/com/develop_ping/union/party/domain/entity/Party.java
  src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
  src/main/java/com/develop_ping/union/photo/domain/service/PhotoServiceImpl.java
  src/main/java/com/develop_ping/union/reaction/domain/ReactionManager.java
  src/main/java/com/develop_ping/union/reaction/infra/ReactionManagerImpl.java
  src/main/java/com/develop_ping/union/reaction/infra/ReactionRepository.java
  src/main/resources/data.sql
Labels: feat

#128 fix: 빼먹은 로직 수정
  src/main/java/com/develop_ping/union/chat/domain/dto/MessageInfo.java
Labels: fix

#131 fix: 채팅방 계속 생성되는 버그 수정
  src/main/java/com/develop_ping/union/chat/infra/ChatroomRepository.java
Labels: fix

#134 feat: 특정 사용자가 참여한 모든 모임 리스트 불러오는 API (#133)
  src/main/java/com/develop_ping/union/party/domain/PartyManager.java
  src/main/java/com/develop_ping/union/party/domain/entity/Party.java
  src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
  src/main/java/com/develop_ping/union/party/infra/PartyRepository.java
Labels: feat

#138 feat: 모임(파티)에 참여한 목록 API (#137)
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringListInfo.java
  src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringListResponse.java
  src/main/java/com/develop_ping/union/party/domain/PartyManager.java
  src/main/java/com/develop_ping/union/party/domain/service/PartyService.java
  src/main/java/com/develop_ping/union/party/domain/service/PartyServiceImpl.java
  src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
  src/main/java/com/develop_ping/union/party/infra/PartyRepository.java
  src/main/java/com/develop_ping/union/party/presentation/PartyController.java
  src/main/java/com/develop_ping/union/party/presentation/response/PartyListResponse.java
Labels: feat, fix

#142 feat: 모임에 참여한 유저 강퇴 API (#141)
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
Labels: feat

#145 feat: 베스트 댓글 API 구현(#144)
  src/main/java/com/develop_ping/union/comment/domain/CommentManager.java
  src/main/java/com/develop_ping/union/comment/domain/dto/CommentInfo.java
  src/main/java/com/develop_ping/union/comment/domain/dto/CommentListInfo.java
  src/main/java/com/develop_ping/union/comment/domain/service/CommentService.java
  src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
  src/main/java/com/develop_ping/union/comment/infra/CommentManagerImpl.java
  src/main/java/com/develop_ping/union/comment/infra/CommentRepository.java
  src/main/java/com/develop_ping/union/comment/presentation/CommentController.java
  src/main/java/com/develop_ping/union/comment/presentation/dto/response/CommentBestResponse.java
Labels: feat

#146 fix: 댓글 is Liked 로직 수정
  src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
Labels: fix

#147 feat: 유저 활동 정보 조회 API 구현(#140)
  src/main/java/com/develop_ping/union/party/domain/PartyManager.java
  src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
  src/main/java/com/develop_ping/union/party/infra/PartyRepository.java
  src/main/java/com/develop_ping/union/post/domain/PostManager.java
  src/main/java/com/develop_ping/union/post/infra/PostManagerImpl.java
  src/main/java/com/develop_ping/union/post/infra/PostRepository.java
  src/main/java/com/develop_ping/union/user/domain/dto/UserStatCommand.java
  src/main/java/com/develop_ping/union/user/domain/dto/UserStatInfo.java
  src/main/java/com/develop_ping/union/user/domain/service/UserService.java
  src/main/java/com/develop_ping/union/user/domain/service/UserServiceImpl.java
  src/main/java/com/develop_ping/union/user/presentation/UserController.java
  src/main/java/com/develop_ping/union/user/presentation/dto/response/UserStatResponse.java
Labels: feat

#148 feat: 내가 참여한 모임 목록 API (#143)
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringListInfo.java
  src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringRepository.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
  src/main/java/com/develop_ping/union/party/presentation/PartyController.java
Labels: feat

#152 chore: Querydsl 환경 설정 (#151)
  build.gradle
Labels: chore

#155 feat: 모임 좋아요 API (#154)
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
Labels: feat

#158 feat: 알림 기능 API 추가 (#157)
  build.gradle
  src/main/java/com/develop_ping/union/notification/domain/NotiType.java
  src/main/java/com/develop_ping/union/notification/domain/NotificationManager.java
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationCommand.java
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationInfo.java
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationListInfo.java
  src/main/java/com/develop_ping/union/notification/domain/entity/Notification.java
  src/main/java/com/develop_ping/union/notification/domain/service/NotificationService.java
  src/main/java/com/develop_ping/union/notification/domain/service/NotificationServiceImpl.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationManagerImpl.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepository.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepositoryCustom.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepositoryCustomImpl.java
  src/main/java/com/develop_ping/union/notification/infra/dto/NotificationReadForService.java
  src/main/java/com/develop_ping/union/notification/presentation/NotificationController.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForCommentRequest.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForGatheringRequest.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForPostRequest.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationCreationForCommentResponse.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationCreationForGatheringResponse.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationCreationForPostResponse.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponse.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponseList.java
  src/main/resources/data.sql
Labels: feat

#160 fix: notification controller dto valid 추가
  src/main/java/com/develop_ping/union/notification/presentation/NotificationController.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForCommentRequest.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForGatheringRequest.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForPostRequest.java
Labels: fix

#163 fix: add typeid in response value
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationInfo.java
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationListInfo.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepositoryCustomImpl.java
  src/main/java/com/develop_ping/union/notification/infra/dto/NotificationReadForService.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponse.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponseList.java
  src/main/resources/data.sql
Labels: fix

#164 feat: 모임 인기글 API (#156)
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringHotListInfo.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/HotGatheringQuery.java
  src/main/java/com/develop_ping/union/gathering/infra/response/GatheringWithLikes.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
  src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringHotListResponse.java
  src/main/resources/data.sql
Labels: feat

#166 Fix: notification read 기능 중 response에 게시판 종류 필드 추가
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationInfo.java
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationListInfo.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepositoryCustomImpl.java
  src/main/java/com/develop_ping/union/notification/infra/dto/NotificationReadForService.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponse.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponseList.java
  src/main/resources/data.sql
Labels: fix

#168 fix: notification 중 isRead 변경 api 작동 방식 수정
  src/main/java/com/develop_ping/union/notification/domain/NotificationManager.java
  src/main/java/com/develop_ping/union/notification/domain/dto/NotificationCommand.java
  src/main/java/com/develop_ping/union/notification/domain/entity/Notification.java
  src/main/java/com/develop_ping/union/notification/domain/service/NotificationService.java
  src/main/java/com/develop_ping/union/notification/domain/service/NotificationServiceImpl.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationManagerImpl.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepository.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepositoryCustom.java
  src/main/java/com/develop_ping/union/notification/infra/NotificationRepositoryCustomImpl.java
  src/main/java/com/develop_ping/union/notification/presentation/NotificationController.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationUpdateIsReadRequest.java
  src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationUpdateIsReadResponse.java
Labels: fix

#170 feat: 모임 목록 list에서 차단 유저 필터링 기능 추가 (#169)
  src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
  src/main/java/com/develop_ping/union/gathering/domain/GatheringSortStrategy.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
  src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
  src/main/java/com/develop_ping/union/gathering/infra/DynamicSortStrategy.java
  src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
  src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
Labels: feat

#172 chore: docker 내에 있는 mysql 한국어 설정 (#171)
  compose.yaml
Labels: chore

#174 refactor: 모임 부분 수정 (#173)
  src/main/java/com/develop_ping/union/gathering/domain/dto/request/GatheringCommand.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringHotListInfo.java
  src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringListInfo.java
  src/main/java/com/develop_ping/union/gathering/presentation/dto/request/GatheringRequest.java
  src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringHotListResponse.java
  src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringListResponse.java
Labels: refactor

#176 chore: 게시글 및 댓글과 관련된 더미데이터 생성(#175)
  src/main/java/com/develop_ping/union/post/domain/entity/PostType.java
  src/main/java/com/develop_ping/union/post/infra/PostManagerImpl.java
  src/main/resources/data.sql
Labels: chore, refactor

#178 chore: 모임 관련 더미데이터 추가(#177)
  src/main/resources/data.sql
Labels: chore

#179 chore: 더미데이터 수정
  src/main/resources/data.sql
Labels: chore

#182 refactor: 모임 current_member 데이터 수정 (#180)
  src/main/resources/data.sql
Labels: refactor
